import type { Metadata } from "next";
import "./globals.css";
import { ClientProvider } from "./components/providers/ClientProvider";
import HomeHeader from "./components/Home/Header/HomeHeader";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "CUNEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        <body className="max-w-[768px] min-h-screen">
          <HomeHeader />
          {children}
        </body>
      </ClientProvider>
    </html>
  );
}
