import type { Metadata } from "next";
import "./globals.css";

import HomeHeader from "./sections/home/home-header";
import ClientProvider from "./components/providers/client-provider";
import ThemeProvider from "./components/providers/theme-provider";

export const metadata: Metadata = {
  title: "CUNEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        <ThemeProvider>
          <body className="max-w-[768px] min-h-screen">
            <HomeHeader />
            {children}
          </body>
        </ThemeProvider>
      </ClientProvider>
    </html>
  );
}
